{{- $namespace := .Values.namespace | default "px-backup" }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ $namespace }}
  name: px-backup-aws-secret
type: Opaque
stringData:
  product-id: d362f7e1-332a-49f2-bf3b-f30e4cf3660c